package edu.eci.ezpz.error;

public enum ErrorCodeEnum {
    CLIENT_NOT_FOUND,
    SELLER_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    MEMBERSHIP_NOT_FOUND,
    EMPTY_MEMBERSHIP_FIELD,
    INVALID_USER_CREDENTIALS
}
